# Generated by Django 4.2 on 2026-02-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id_servicio', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.FloatField(blank=True, null=True)),
                ('ubicacion_lat', models.FloatField(blank=True, null=True)),
                ('ubicacion_lon', models.FloatField(blank=True, null=True)),
                ('imagen_url', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_SERVICIOS',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TIPOS_SERVICIO',
            },
        ),
        migrations.CreateModel(
            name='DetalleActividad',
            fields=[
                ('servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_actividad', serialize=False, to='marketdata.catalogoservicio')),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('aforo_maximo', models.IntegerField(blank=True, null=True)),
                ('horario_apertura', models.TextField(blank=True, null=True)),
                ('guia_incluido', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DETALLE_ACTIVIDAD',
            },
        ),
        migrations.CreateModel(
            name='DetalleAlojamiento',
            fields=[
                ('servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_alojamiento', serialize=False, to='marketdata.catalogoservicio')),
                ('estrellas', models.IntegerField(blank=True, null=True)),
                ('hora_checkin', models.TimeField(blank=True, null=True)),
                ('hora_checkout', models.TimeField(blank=True, null=True)),
                ('servicios_extra', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DETALLE_ALOJAMIENTO',
            },
        ),
        migrations.CreateModel(
            name='DetalleRestauracion',
            fields=[
                ('servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_restauracion', serialize=False, to='marketdata.catalogoservicio')),
                ('tipo_cocina', models.TextField(blank=True, null=True)),
                ('es_vegano', models.BooleanField(blank=True, null=True)),
                ('precio_medio', models.FloatField(blank=True, null=True)),
                ('requiere_reserva', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DETALLE_RESTAURACION',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransporte',
            fields=[
                ('servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_transporte', serialize=False, to='marketdata.catalogoservicio')),
                ('ciudad_origen', models.TextField(blank=True, null=True)),
                ('ciudad_destino', models.TextField(blank=True, null=True)),
                ('compania', models.TextField(blank=True, null=True)),
                ('codigo_vuelo', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DETALLE_TRANSPORTE',
            },
        ),
        migrations.AddField(
            model_name='catalogoservicio',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='marketdata.tiposervicio'),
        ),
    ]
