# Generated by Django 4.2 on 2026-05-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_catalogoservicio_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleactividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='detallealojamiento',
            options={'verbose_name': 'Alojamiento', 'verbose_name_plural': 'Alojamientos'},
        ),
        migrations.AlterModelOptions(
            name='detallerestauracion',
            options={'verbose_name': 'Restauración', 'verbose_name_plural': 'Restauraciones'},
        ),
        migrations.AlterModelOptions(
            name='detalletransporte',
            options={'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
    ]
