# Generated by Django 4.2 on 2026-05-05 09:19

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_planings'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='actividades',
            field=models.JSONField(blank=True, default=list, help_text='Lista de actividades del vendedor', verbose_name='Actividades'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alojamientos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de alojamientos del vendedor', verbose_name='Alojamientos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='planings',
            field=models.JSONField(blank=True, default=list, help_text='Lista de planes de viaje del usuario', verbose_name='Plannings'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='restaurantes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de restaurantes del vendedor', verbose_name='Restaurantes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
