from django.core.management.base import BaseCommand
from marketdata.models import (
    TipoServicio, CatalogoServicio,
    DetalleAlojamiento, DetalleTransporte,
    DetalleRestauracion, DetalleActividad,
)

TIPOS = [
    {"nombre_tipo": "Alojamiento", "icono": "hotel"},
    {"nombre_tipo": "Transporte",  "icono": "flight"},
    {"nombre_tipo": "Restauración","icono": "restaurant"},
    {"nombre_tipo": "Actividad",   "icono": "local_activity"},
]

ALOJAMIENTOS = [
    {
        "id": "aloj-001",
        "servicio": {
            "nombre": "Westin Palace Madrid",
            "descripcion": "Hotel de lujo centenario frente al Paseo del Prado. Cúpula de cristal icónica en el corazón de Madrid.",
            "precio_base": 380.0, "ubicacion_lat": 40.4153, "ubicacion_lon": -3.6937,
            "imagen_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, gimnasio, La Rotonda restaurante, servicio de conserjería 24h"},
    },
    {
        "id": "aloj-002",
        "servicio": {
            "nombre": "Hotel Arts Barcelona",
            "descripcion": "Rascacielos de 44 plantas frente al mar en la Vila Olímpica. Vistas panorámicas al Mediterráneo.",
            "precio_base": 450.0, "ubicacion_lat": 41.3871, "ubicacion_lon": 2.1975,
            "imagen_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa Ritz-Carlton, piscina exterior, Enoteca (2 estrellas Michelin), acceso privado a la playa"},
    },
    {
        "id": "aloj-003",
        "servicio": {
            "nombre": "Parador de Granada",
            "descripcion": "Antiguo convento franciscano del siglo XV dentro del recinto de la Alhambra, Granada.",
            "precio_base": 320.0, "ubicacion_lat": 37.1771, "ubicacion_lon": -3.5882,
            "imagen_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Jardines históricos, restaurante andaluz, acceso privilegiado a la Alhambra"},
    },
    {
        "id": "aloj-004",
        "servicio": {
            "nombre": "Hotel María Cristina San Sebastián",
            "descripcion": "Icónico hotel belle époque a orillas del río Urumea, sede del Festival de Cine de San Sebastián.",
            "precio_base": 520.0, "ubicacion_lat": 43.3213, "ubicacion_lon": -1.9784,
            "imagen_url": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, restaurante Café Saigón, salones históricos, a 5 min de la Playa de la Concha"},
    },
    {
        "id": "aloj-005",
        "servicio": {
            "nombre": "Gran Hotel Miramar Málaga",
            "descripcion": "Palacete modernista del siglo XX frente a la playa de La Malagueta, Málaga.",
            "precio_base": 290.0, "ubicacion_lat": 36.7195, "ubicacion_lon": -4.4080,
            "imagen_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, piscina exterior, restaurante El Palmeral, vistas al Mediterráneo"},
    },
    {
        "id": "aloj-006",
        "servicio": {
            "nombre": "Nixe Palace Palma de Mallorca",
            "descripcion": "Hotel boutique de lujo con acceso directo al mar en Cala Major, Palma de Mallorca.",
            "precio_base": 410.0, "ubicacion_lat": 39.5517, "ubicacion_lon": 2.6024,
            "imagen_url": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
            "disponible": False,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, piscina sobre el mar, restaurante de cocina mallorquina, club náutico"},
    },
    {
        "id": "aloj-007",
        "servicio": {
            "nombre": "Hotel Alfonso XIII — Sevilla",
            "descripcion": "Palacio mudéjar de 1928 en el corazón de Sevilla, símbolo del lujo andaluz.",
            "precio_base": 420.0, "ubicacion_lat": 37.3840, "ubicacion_lon": -5.9953,
            "imagen_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, piscina exterior, restaurante San Fernando, jardines históricos"},
    },
    {
        "id": "aloj-008",
        "servicio": {
            "nombre": "Gran Hotel Domine — Bilbao",
            "descripcion": "Diseño vanguardista frente al Museo Guggenheim Bilbao, referente de la arquitectura contemporánea.",
            "precio_base": 310.0, "ubicacion_lat": 43.2688, "ubicacion_lon": -2.9341,
            "imagen_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Vistas directas al Guggenheim, restaurante Mina, bar Sky Lounge"},
    },
    {
        "id": "aloj-009",
        "servicio": {
            "nombre": "Parador de Toledo",
            "descripcion": "Clásico parador con vistas panorámicas a la ciudad imperial de Toledo y el río Tajo.",
            "precio_base": 180.0, "ubicacion_lat": 39.8581, "ubicacion_lon": -4.0227,
            "imagen_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Piscina, restaurante toledano, terrazas con vistas al Tajo y la catedral"},
    },
    {
        "id": "aloj-010",
        "servicio": {
            "nombre": "Hotel Hacienda Na Xamena — Ibiza",
            "descripcion": "Único hotel-fortaleza suspendido sobre los acantilados al norte de Ibiza. Privacidad absoluta.",
            "precio_base": 680.0, "ubicacion_lat": 39.0543, "ubicacion_lon": 1.3697,
            "imagen_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "3 piscinas en cascada sobre el mar, spa, restaurante ibicenco, helipuerto"},
    },
    {
        "id": "aloj-011",
        "servicio": {
            "nombre": "Las Arenas Balneario Resort — Valencia",
            "descripcion": "Elegante resort belle époque a pie de playa en La Malvarrosa, Valencia.",
            "precio_base": 265.0, "ubicacion_lat": 39.4849, "ubicacion_lon": -0.3278,
            "imagen_url": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa termal, acceso directo a la playa, 2 restaurantes"},
    },
    {
        "id": "aloj-012",
        "servicio": {
            "nombre": "Hotel Viura — Villabuena de Álava",
            "descripcion": "Hotel de diseño cúbico en el corazón de La Rioja Alavesa, entre viñedos centenarios.",
            "precio_base": 190.0, "ubicacion_lat": 42.5793, "ubicacion_lon": -2.7089,
            "imagen_url": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Catas de vino, restaurante de cocina vasca, terrazas sobre los viñedos"},
    },
    {
        "id": "aloj-013",
        "servicio": {
            "nombre": "Hospes Palau de la Mar — Valencia",
            "descripcion": "Palacio neoclásico del siglo XIX convertido en hotel boutique en el centro de Valencia.",
            "precio_base": 230.0, "ubicacion_lat": 39.4702, "ubicacion_lon": -0.3750,
            "imagen_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa Bodyna, piscina climatizada, restaurante Vertical"},
    },
    {
        "id": "aloj-014",
        "servicio": {
            "nombre": "Hotel Palacio del Bailio — Córdoba",
            "descripcion": "Palacio renacentista del s. XVI con restos arqueológicos romanos visibles en el suelo.",
            "precio_base": 210.0, "ubicacion_lat": 37.8813, "ubicacion_lon": -4.7797,
            "imagen_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Piscina en patio romano, spa, restaurante El Novecentro"},
    },
    {
        "id": "aloj-015",
        "servicio": {
            "nombre": "Parador de Salamanca",
            "descripcion": "Moderno parador con vistas únicas a la Catedral y el casco histórico de Salamanca.",
            "precio_base": 165.0, "ubicacion_lat": 40.9673, "ubicacion_lon": -5.6635,
            "imagen_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Piscina, restaurante castellano, terraza con vistas a la catedral"},
    },
    {
        "id": "aloj-016",
        "servicio": {
            "nombre": "Hotel Pleta de Mar — Canyamel, Mallorca",
            "descripcion": "Lujoso resort de cinco estrellas sobre los acantilados de Canyamel, Mallorca.",
            "precio_base": 560.0, "ubicacion_lat": 39.7228, "ubicacion_lon": 3.4451,
            "imagen_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, 2 piscinas infinitas, restaurante de autor, acceso privado a cala"},
    },
    {
        "id": "aloj-017",
        "servicio": {
            "nombre": "AC Hotel Palacio de Santa Ana — Valladolid",
            "descripcion": "Convento dominico del siglo XV rehabilitado como hotel boutique en el centro de Valladolid.",
            "precio_base": 135.0, "ubicacion_lat": 41.6489, "ubicacion_lon": -4.7285,
            "imagen_url": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Claustro original, restaurante castellano, bar en antigua cripta"},
    },
    {
        "id": "aloj-018",
        "servicio": {
            "nombre": "Parador de Ronda",
            "descripcion": "Antiguo ayuntamiento del siglo XVIII junto al famoso Tajo de Ronda, Málaga.",
            "precio_base": 175.0, "ubicacion_lat": 36.7461, "ubicacion_lon": -5.1663,
            "imagen_url": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Terraza sobre el Tajo, piscina, restaurante de cocina andaluza"},
    },
    {
        "id": "aloj-019",
        "servicio": {
            "nombre": "Hotel Santa Catalina — Las Palmas de Gran Canaria",
            "descripcion": "Hotel centenario de estilo colonial inglés en el barrio de Triana, Las Palmas.",
            "precio_base": 200.0, "ubicacion_lat": 28.1317, "ubicacion_lon": -15.4367,
            "imagen_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Piscina exterior, spa, restaurante colonial, jardines tropicales"},
    },
    {
        "id": "aloj-020",
        "servicio": {
            "nombre": "Finca Cortesín Hotel — Casares, Málaga",
            "descripcion": "Resort de lujo entre Marbella y Sotogrande con uno de los mejores campos de golf de Europa.",
            "precio_base": 750.0, "ubicacion_lat": 36.4132, "ubicacion_lon": -5.2543,
            "imagen_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Campo de golf 18 hoyos, spa, 3 piscinas, restaurante Kabuki Raw"},
    },
    {
        "id": "aloj-021",
        "servicio": {
            "nombre": "Abama Golf & Spa Resort — Tenerife",
            "descripcion": "Resort de lujo en la costa oeste de Tenerife con golf y restaurante 2 estrellas Michelin.",
            "precio_base": 490.0, "ubicacion_lat": 28.1532, "ubicacion_lon": -16.8276,
            "imagen_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Golf 18 hoyos, 9 piscinas, Kabuki (2 Michelin), spa, playa privada"},
    },
    {
        "id": "aloj-022",
        "servicio": {
            "nombre": "Hotel Casa de las Cuatro Torres — Cádiz",
            "descripcion": "Casa palaciega del siglo XVIII en el centro histórico de Cádiz, la ciudad más antigua de Europa.",
            "precio_base": 145.0, "ubicacion_lat": 36.5297, "ubicacion_lon": -6.2900,
            "imagen_url": "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Azotea con vistas al océano, desayuno gourmet, patio andaluz"},
    },
    {
        "id": "aloj-023",
        "servicio": {
            "nombre": "Echaurren Hotel — Ezcaray, La Rioja",
            "descripcion": "El hotel-restaurante más antiguo de España con estrella Michelin, en el valle del río Oja.",
            "precio_base": 155.0, "ubicacion_lat": 42.3172, "ubicacion_lon": -3.0090,
            "imagen_url": "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 4, "hora_checkin": "14:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Restaurante Echaurren 1 Michelin, bodega propia, spa nórdico"},
    },
    {
        "id": "aloj-024",
        "servicio": {
            "nombre": "Parador de Santiago de Compostela",
            "descripcion": "El hotel más antiguo del mundo en activo (1499), en la Plaza del Obradoiro frente a la Catedral.",
            "precio_base": 340.0, "ubicacion_lat": 42.8805, "ubicacion_lon": -8.5449,
            "imagen_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "4 restaurantes, claustros históricos, capilla, vistas a la catedral"},
    },
    {
        "id": "aloj-025",
        "servicio": {
            "nombre": "Hotel El Palace — Barcelona",
            "descripcion": "Hotel art déco de 1919 en el Eixample barcelonés, icono histórico de la ciudad condal.",
            "precio_base": 395.0, "ubicacion_lat": 41.3897, "ubicacion_lon": 2.1686,
            "imagen_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, piscina en azotea, restaurante Comes & Bebe, bar Gimlet"},
    },
    {
        "id": "aloj-026",
        "servicio": {
            "nombre": "La Bobadilla Royal Hideaway — Loja, Granada",
            "descripcion": "Villa andaluza de lujo en plena campiña granadina, a 45 min de la Alhambra.",
            "precio_base": 380.0, "ubicacion_lat": 37.1652, "ubicacion_lon": -4.1567,
            "imagen_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
            "disponible": True,
        },
        "detalle": {"estrellas": 5, "hora_checkin": "15:00:00", "hora_checkout": "12:00:00",
                    "servicios_extra": "Spa, piscina, restaurante La Finca, pistas de tenis, naturaleza"},
    },
]

TRANSPORTES = [
    {
        "id": "tran-001",
        "servicio": {
            "nombre": "Vuelo Madrid → Barcelona — Iberia IB-1622",
            "descripcion": "Vuelo directo de Madrid Barajas a Barcelona El Prat operado por Iberia.",
            "precio_base": 89.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Barcelona (BCN)",
                    "compania": "Iberia", "codigo_vuelo": "IB-1622", "duracion_minutos": 75},
    },
    {
        "id": "tran-002",
        "servicio": {
            "nombre": "AVE Madrid → Sevilla — Renfe AVE S-104",
            "descripcion": "Tren de alta velocidad entre Madrid Atocha y Sevilla Santa Justa. 2h30min.",
            "precio_base": 65.0, "ubicacion_lat": 40.4066, "ubicacion_lon": -3.6897,
            "imagen_url": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (Atocha)", "ciudad_destino": "Sevilla (Santa Justa)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S104", "duracion_minutos": 150},
    },
    {
        "id": "tran-003",
        "servicio": {
            "nombre": "Vuelo Barcelona → Palma — Vueling VY-1802",
            "descripcion": "Vuelo directo de Barcelona El Prat a Palma de Mallorca operado por Vueling.",
            "precio_base": 55.0, "ubicacion_lat": 41.2971, "ubicacion_lon": 2.0785,
            "imagen_url": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Barcelona (BCN)", "ciudad_destino": "Palma de Mallorca (PMI)",
                    "compania": "Vueling", "codigo_vuelo": "VY-1802", "duracion_minutos": 50},
    },
    {
        "id": "tran-004",
        "servicio": {
            "nombre": "Vuelo Madrid → Tenerife Norte — Iberia IB-710",
            "descripcion": "Vuelo directo de Madrid Barajas al Aeropuerto de Tenerife Norte.",
            "precio_base": 130.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Tenerife Norte (TFN)",
                    "compania": "Iberia", "codigo_vuelo": "IB-710", "duracion_minutos": 165},
    },
    {
        "id": "tran-005",
        "servicio": {
            "nombre": "Vuelo Madrid → Bilbao — Air Nostrum IB-8756",
            "descripcion": "Vuelo regional de Madrid Barajas al Aeropuerto de Bilbao-Loiu.",
            "precio_base": 75.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Bilbao (BIO)",
                    "compania": "Air Nostrum", "codigo_vuelo": "IB-8756", "duracion_minutos": 60},
    },
    {
        "id": "tran-006",
        "servicio": {
            "nombre": "Vuelo Sevilla → Ibiza — Ryanair FR-5540",
            "descripcion": "Vuelo directo de Sevilla a Ibiza operado por Ryanair. Temporada de verano.",
            "precio_base": 48.0, "ubicacion_lat": 37.4180, "ubicacion_lon": -5.8931,
            "imagen_url": "https://images.unsplash.com/photo-1540339832862-474599807836?w=800",
            "disponible": False,
        },
        "detalle": {"ciudad_origen": "Sevilla (SVQ)", "ciudad_destino": "Ibiza (IBZ)",
                    "compania": "Ryanair", "codigo_vuelo": "FR-5540", "duracion_minutos": 80},
    },
    {
        "id": "tran-007",
        "servicio": {
            "nombre": "AVE Madrid → Valencia — Renfe AVE S-112",
            "descripcion": "Alta velocidad entre Atocha y Joaquín Sorolla. 1h 35min por la vía de nueva construcción.",
            "precio_base": 49.0, "ubicacion_lat": 40.4066, "ubicacion_lon": -3.6897,
            "imagen_url": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (Atocha)", "ciudad_destino": "Valencia (Joaquín Sorolla)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S112", "duracion_minutos": 95},
    },
    {
        "id": "tran-008",
        "servicio": {
            "nombre": "AVE Madrid → Málaga — Renfe AVE S-103",
            "descripcion": "Alta velocidad de Madrid a Málaga en 2h 25min. Puerta al sol de la Costa del Sol.",
            "precio_base": 58.0, "ubicacion_lat": 40.4066, "ubicacion_lon": -3.6897,
            "imagen_url": "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (Atocha)", "ciudad_destino": "Málaga (María Zambrano)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S103", "duracion_minutos": 145},
    },
    {
        "id": "tran-009",
        "servicio": {
            "nombre": "AVE Madrid → Zaragoza — Renfe AVE S-102",
            "descripcion": "Alta velocidad entre Madrid y Zaragoza. 1h 15min. Perfecta conexión con el norte.",
            "precio_base": 38.0, "ubicacion_lat": 40.4066, "ubicacion_lon": -3.6897,
            "imagen_url": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (Atocha)", "ciudad_destino": "Zaragoza (Delicias)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S102", "duracion_minutos": 75},
    },
    {
        "id": "tran-010",
        "servicio": {
            "nombre": "Vuelo Madrid → Lanzarote — Iberia IB-756",
            "descripcion": "Vuelo directo de Madrid a Lanzarote, la isla del fuego. Paisajes volcánicos únicos.",
            "precio_base": 115.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Lanzarote (ACE)",
                    "compania": "Iberia", "codigo_vuelo": "IB-756", "duracion_minutos": 150},
    },
    {
        "id": "tran-011",
        "servicio": {
            "nombre": "Vuelo Madrid → Gran Canaria — Iberia IB-762",
            "descripcion": "Vuelo directo a Gran Canaria, el continente en miniatura. Dunas, ciudades y laurisilva.",
            "precio_base": 125.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Gran Canaria (LPA)",
                    "compania": "Iberia", "codigo_vuelo": "IB-762", "duracion_minutos": 170},
    },
    {
        "id": "tran-012",
        "servicio": {
            "nombre": "Vuelo Barcelona → Ibiza — Vueling VY-1812",
            "descripcion": "Vuelo directo de Barcelona a Ibiza en temporada de verano. 55 minutos.",
            "precio_base": 42.0, "ubicacion_lat": 41.2971, "ubicacion_lon": 2.0785,
            "imagen_url": "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Barcelona (BCN)", "ciudad_destino": "Ibiza (IBZ)",
                    "compania": "Vueling", "codigo_vuelo": "VY-1812", "duracion_minutos": 55},
    },
    {
        "id": "tran-013",
        "servicio": {
            "nombre": "Ferry Barcelona → Palma — Baleàlia Ferries",
            "descripcion": "Ferry nocturno de lujo entre Barcelona y Palma de Mallorca. Camarotes y restaurante a bordo.",
            "precio_base": 90.0, "ubicacion_lat": 41.3502, "ubicacion_lon": 2.1642,
            "imagen_url": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Barcelona (Puerto)", "ciudad_destino": "Palma de Mallorca (Puerto)",
                    "compania": "Baleàlia Ferries", "codigo_vuelo": "BF-101", "duracion_minutos": 465},
    },
    {
        "id": "tran-014",
        "servicio": {
            "nombre": "Vuelo Barcelona → Tenerife Sur — Vueling VY-3852",
            "descripcion": "Vuelo directo de Barcelona El Prat a Tenerife Sur. 2h 30min sobre el Atlántico.",
            "precio_base": 98.0, "ubicacion_lat": 41.2971, "ubicacion_lon": 2.0785,
            "imagen_url": "https://images.unsplash.com/photo-1540339832862-474599807836?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Barcelona (BCN)", "ciudad_destino": "Tenerife Sur (TFS)",
                    "compania": "Vueling", "codigo_vuelo": "VY-3852", "duracion_minutos": 150},
    },
    {
        "id": "tran-015",
        "servicio": {
            "nombre": "Vuelo Madrid → Santiago de Compostela — Iberia IB-730",
            "descripcion": "Vuelo directo de Madrid al aeropuerto de Santiago de Compostela. 1h 05min.",
            "precio_base": 72.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Santiago de Compostela (SCQ)",
                    "compania": "Iberia", "codigo_vuelo": "IB-730", "duracion_minutos": 65},
    },
    {
        "id": "tran-016",
        "servicio": {
            "nombre": "AVE Madrid → Alicante — Renfe AVE S-130",
            "descripcion": "Alta velocidad entre Madrid y Alicante. 2h 20min. Acceso a la Costa Blanca.",
            "precio_base": 55.0, "ubicacion_lat": 40.4066, "ubicacion_lon": -3.6897,
            "imagen_url": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (Atocha)", "ciudad_destino": "Alicante (Término)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S130", "duracion_minutos": 140},
    },
    {
        "id": "tran-017",
        "servicio": {
            "nombre": "Vuelo Bilbao → Barcelona — Vueling VY-1254",
            "descripcion": "Vuelo directo entre Bilbao-Loiu y Barcelona El Prat. 1h 15min.",
            "precio_base": 65.0, "ubicacion_lat": 43.3010, "ubicacion_lon": -2.9106,
            "imagen_url": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Bilbao (BIO)", "ciudad_destino": "Barcelona (BCN)",
                    "compania": "Vueling", "codigo_vuelo": "VY-1254", "duracion_minutos": 75},
    },
    {
        "id": "tran-018",
        "servicio": {
            "nombre": "Vuelo Madrid → Vigo — Air Nostrum IB-8760",
            "descripcion": "Vuelo regional entre Madrid y Vigo. Puerta de entrada a las Rías Baixas gallegas.",
            "precio_base": 68.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Vigo (VGO)",
                    "compania": "Air Nostrum", "codigo_vuelo": "IB-8760", "duracion_minutos": 65},
    },
    {
        "id": "tran-019",
        "servicio": {
            "nombre": "Ferry Algeciras → Ceuta — Baleària",
            "descripcion": "Cruce rápido del Estrecho de Gibraltar. 35 minutos entre Europa y África.",
            "precio_base": 28.0, "ubicacion_lat": 36.1408, "ubicacion_lon": -5.4532,
            "imagen_url": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Algeciras (Puerto)", "ciudad_destino": "Ceuta (Puerto)",
                    "compania": "Baleària", "codigo_vuelo": "BA-C01", "duracion_minutos": 35},
    },
    {
        "id": "tran-020",
        "servicio": {
            "nombre": "AVE Madrid → Valladolid — Renfe AVE S-114",
            "descripcion": "Alta velocidad entre Madrid y Valladolid. Solo 55 minutos. Conexión frecuente.",
            "precio_base": 28.0, "ubicacion_lat": 40.4066, "ubicacion_lon": -3.6897,
            "imagen_url": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (Atocha)", "ciudad_destino": "Valladolid (Campo Grande)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S114", "duracion_minutos": 55},
    },
    {
        "id": "tran-021",
        "servicio": {
            "nombre": "Vuelo Madrid → Menorca — Air Nostrum IB-8816",
            "descripcion": "Vuelo regional de Madrid a Menorca. Acceso a la isla más tranquila de las Baleares.",
            "precio_base": 82.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Menorca (MAH)",
                    "compania": "Air Nostrum", "codigo_vuelo": "IB-8816", "duracion_minutos": 100},
    },
    {
        "id": "tran-022",
        "servicio": {
            "nombre": "Vuelo Madrid → Almería — Iberia Regional IB-8820",
            "descripcion": "Vuelo regional entre Madrid y Almería. Puerta al desierto de Tabernas y el Cabo de Gata.",
            "precio_base": 59.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Almería (LEI)",
                    "compania": "Iberia Regional", "codigo_vuelo": "IB-8820", "duracion_minutos": 70},
    },
    {
        "id": "tran-023",
        "servicio": {
            "nombre": "Vuelo Barcelona → Bilbao — Vueling VY-1262",
            "descripcion": "Vuelo directo de Barcelona a Bilbao. 55 minutos, frecuencia diaria.",
            "precio_base": 58.0, "ubicacion_lat": 41.2971, "ubicacion_lon": 2.0785,
            "imagen_url": "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Barcelona (BCN)", "ciudad_destino": "Bilbao (BIO)",
                    "compania": "Vueling", "codigo_vuelo": "VY-1262", "duracion_minutos": 55},
    },
    {
        "id": "tran-024",
        "servicio": {
            "nombre": "Vuelo Madrid → Jerez — Iberia Regional IB-8832",
            "descripcion": "Vuelo regional entre Madrid y Jerez de la Frontera. Puerta al Marco de Jerez.",
            "precio_base": 54.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Jerez de la Frontera (XRY)",
                    "compania": "Iberia Regional", "codigo_vuelo": "IB-8832", "duracion_minutos": 60},
    },
    {
        "id": "tran-025",
        "servicio": {
            "nombre": "AVE Barcelona → Valencia — Renfe AVE S-121",
            "descripcion": "Alta velocidad entre Barcelona Sants y Valencia Joaquín Sorolla. 3h 05min.",
            "precio_base": 45.0, "ubicacion_lat": 41.3790, "ubicacion_lon": 2.1403,
            "imagen_url": "https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800",
            "disponible": True,
        },
        "detalle": {"ciudad_origen": "Barcelona (Sants)", "ciudad_destino": "Valencia (Joaquín Sorolla)",
                    "compania": "Renfe AVE", "codigo_vuelo": "AVE-S121", "duracion_minutos": 185},
    },
    {
        "id": "tran-026",
        "servicio": {
            "nombre": "Vuelo Madrid → Fuerteventura — Iberia IB-774",
            "descripcion": "Vuelo directo entre Madrid y Fuerteventura, la isla de las playas infinitas.",
            "precio_base": 120.0, "ubicacion_lat": 40.4983, "ubicacion_lon": -3.5676,
            "imagen_url": "https://images.unsplash.com/photo-1540339832862-474599807836?w=800",
            "disponible": False,
        },
        "detalle": {"ciudad_origen": "Madrid (MAD)", "ciudad_destino": "Fuerteventura (FUE)",
                    "compania": "Iberia", "codigo_vuelo": "IB-774", "duracion_minutos": 160},
    },
]

RESTAURACIONES = [
    {
        "id": "rest-001",
        "servicio": {
            "nombre": "DiverXO — Madrid",
            "descripcion": "Único restaurante con 3 estrellas Michelin en Madrid. Chef Dabiz Muñoz. Cocina asiático-española de vanguardia.",
            "precio_base": 365.0, "ubicacion_lat": 40.4587, "ubicacion_lon": -3.6909,
            "imagen_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Vanguardia asiático-española", "es_vegano": False,
                    "precio_medio": 365.0, "requiere_reserva": True},
    },
    {
        "id": "rest-002",
        "servicio": {
            "nombre": "El Celler de Can Roca — Girona",
            "descripcion": "3 estrellas Michelin. Los hermanos Roca crean en Girona una de las experiencias gastronómicas más aclamadas del planeta.",
            "precio_base": 280.0, "ubicacion_lat": 41.9838, "ubicacion_lon": 2.8082,
            "imagen_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Alta cocina catalana", "es_vegano": False,
                    "precio_medio": 280.0, "requiere_reserva": True},
    },
    {
        "id": "rest-003",
        "servicio": {
            "nombre": "Martín Berasategui — Lasarte-Oria",
            "descripcion": "3 estrellas Michelin en el País Vasco. El chef con más estrellas de España.",
            "precio_base": 310.0, "ubicacion_lat": 43.2672, "ubicacion_lon": -2.0138,
            "imagen_url": "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Alta cocina vasca", "es_vegano": False,
                    "precio_medio": 310.0, "requiere_reserva": True},
    },
    {
        "id": "rest-004",
        "servicio": {
            "nombre": "Casa Bigote — Sanlúcar de Barrameda",
            "descripcion": "Taberna legendaria a orillas del Guadalquivir. Langostinos de Sanlúcar y vinos de la tierra desde 1962.",
            "precio_base": 55.0, "ubicacion_lat": 36.7769, "ubicacion_lon": -6.3589,
            "imagen_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Marinera andaluza", "es_vegano": False,
                    "precio_medio": 55.0, "requiere_reserva": False},
    },
    {
        "id": "rest-005",
        "servicio": {
            "nombre": "Teresa Carles — Barcelona",
            "descripcion": "El restaurante vegano de referencia en Barcelona. Cocina creativa con productos de temporada y proximidad.",
            "precio_base": 35.0, "ubicacion_lat": 41.3838, "ubicacion_lon": 2.1668,
            "imagen_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Vegetariana y vegana creativa", "es_vegano": True,
                    "precio_medio": 35.0, "requiere_reserva": False},
    },
    {
        "id": "rest-006",
        "servicio": {
            "nombre": "Quique Dacosta — Dénia",
            "descripcion": "3 estrellas Michelin en la Marina Alta alicantina. Reinterpretación del recetario mediterráneo.",
            "precio_base": 290.0, "ubicacion_lat": 38.8400, "ubicacion_lon": 0.1079,
            "imagen_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Alta cocina mediterránea", "es_vegano": False,
                    "precio_medio": 290.0, "requiere_reserva": True},
    },
    {
        "id": "rest-007",
        "servicio": {
            "nombre": "Tickets — Barcelona",
            "descripcion": "Tapas de vanguardia de los hermanos Adrià en el barrio del Paralel. Gastronomía lúdica y sorprendente.",
            "precio_base": 120.0, "ubicacion_lat": 41.3751, "ubicacion_lon": 2.1632,
            "imagen_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Tapas de vanguardia", "es_vegano": False,
                    "precio_medio": 120.0, "requiere_reserva": True},
    },
    {
        "id": "rest-008",
        "servicio": {
            "nombre": "Disfrutar — Barcelona",
            "descripcion": "3 estrellas Michelin. Cocina de vanguardia de tres ex-alumnos de elBulli. N.º 2 del mundo en 2024.",
            "precio_base": 250.0, "ubicacion_lat": 41.3924, "ubicacion_lon": 2.1570,
            "imagen_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Alta cocina de vanguardia", "es_vegano": False,
                    "precio_medio": 250.0, "requiere_reserva": True},
    },
    {
        "id": "rest-009",
        "servicio": {
            "nombre": "Arzak — San Sebastián",
            "descripcion": "3 estrellas Michelin. La casa del chef Juan Mari Arzak, padre de la nueva cocina vasca, desde 1897.",
            "precio_base": 280.0, "ubicacion_lat": 43.3050, "ubicacion_lon": -1.9576,
            "imagen_url": "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Nueva cocina vasca", "es_vegano": False,
                    "precio_medio": 280.0, "requiere_reserva": True},
    },
    {
        "id": "rest-010",
        "servicio": {
            "nombre": "Akelarre — San Sebastián",
            "descripcion": "3 estrellas Michelin con vistas al Cantábrico. Chef Pedro Subijana. Cocina vasca evolutiva.",
            "precio_base": 265.0, "ubicacion_lat": 43.3099, "ubicacion_lon": -2.0011,
            "imagen_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina vasca evolutiva", "es_vegano": False,
                    "precio_medio": 265.0, "requiere_reserva": True},
    },
    {
        "id": "rest-011",
        "servicio": {
            "nombre": "Mesón de Cándido — Segovia",
            "descripcion": "Restaurante centenario especializado en el mejor cochinillo segoviano. Declarado Patrimonio Gastronómico.",
            "precio_base": 55.0, "ubicacion_lat": 40.9487, "ubicacion_lon": -4.1185,
            "imagen_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina castellana tradicional", "es_vegano": False,
                    "precio_medio": 55.0, "requiere_reserva": True},
    },
    {
        "id": "rest-012",
        "servicio": {
            "nombre": "Bar El Faro — Cádiz",
            "descripcion": "El templo del pescado y marisco gaditano. Frituras de pescado y ortiguillas únicas en el mundo.",
            "precio_base": 45.0, "ubicacion_lat": 36.5297, "ubicacion_lon": -6.2949,
            "imagen_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Marinera gaditana", "es_vegano": False,
                    "precio_medio": 45.0, "requiere_reserva": False},
    },
    {
        "id": "rest-013",
        "servicio": {
            "nombre": "La Pepica — Valencia",
            "descripcion": "El restaurante de paella más famoso de Valencia, a orillas de La Malvarrosa desde 1898.",
            "precio_base": 40.0, "ubicacion_lat": 39.4839, "ubicacion_lon": -0.3271,
            "imagen_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Arroces y paellas valencianas", "es_vegano": False,
                    "precio_medio": 40.0, "requiere_reserva": True},
    },
    {
        "id": "rest-014",
        "servicio": {
            "nombre": "El Bohío — Illescas, Toledo",
            "descripcion": "2 estrellas Michelin en Toledo. Chef Pepe Rodríguez (MasterChef). Cocina manchega de autor.",
            "precio_base": 145.0, "ubicacion_lat": 40.1213, "ubicacion_lon": -3.8458,
            "imagen_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina manchega de autor", "es_vegano": False,
                    "precio_medio": 145.0, "requiere_reserva": True},
    },
    {
        "id": "rest-015",
        "servicio": {
            "nombre": "Bodega El Capricho — Jiménez de Jamuz, León",
            "descripcion": "El templo del buey y el chuletón en España. Carnes maduradas de más de 200 días. Solo para carnívoros.",
            "precio_base": 95.0, "ubicacion_lat": 42.2754, "ubicacion_lon": -5.9567,
            "imagen_url": "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Parrilla de carnes maduradas", "es_vegano": False,
                    "precio_medio": 95.0, "requiere_reserva": True},
    },
    {
        "id": "rest-016",
        "servicio": {
            "nombre": "Casa Solla — San Salvador de Poio, Pontevedra",
            "descripcion": "1 estrella Michelin. Cocina gallega de producto en un antiguo pazo frente a la ría de Pontevedra.",
            "precio_base": 130.0, "ubicacion_lat": 42.4316, "ubicacion_lon": -8.6462,
            "imagen_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Alta cocina gallega", "es_vegano": False,
                    "precio_medio": 130.0, "requiere_reserva": True},
    },
    {
        "id": "rest-017",
        "servicio": {
            "nombre": "El Choco — Córdoba",
            "descripcion": "1 estrella Michelin. El chef Kisko García reinterpreta la cocina cordobesa con técnica y creatividad.",
            "precio_base": 110.0, "ubicacion_lat": 37.8882, "ubicacion_lon": -4.7794,
            "imagen_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina cordobesa contemporánea", "es_vegano": False,
                    "precio_medio": 110.0, "requiere_reserva": True},
    },
    {
        "id": "rest-018",
        "servicio": {
            "nombre": "Casa Gerardo — Prendes, Asturias",
            "descripcion": "1 estrella Michelin. Fabada asturiana y cocina de mar del Cantábrico. 5 generaciones de tradición.",
            "precio_base": 90.0, "ubicacion_lat": 43.5112, "ubicacion_lon": -5.9157,
            "imagen_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina asturiana de autor", "es_vegano": False,
                    "precio_medio": 90.0, "requiere_reserva": True},
    },
    {
        "id": "rest-019",
        "servicio": {
            "nombre": "Cinco Jotas Jabugo — Jabugo, Huelva",
            "descripcion": "La experiencia definitiva del jamón ibérico de bellota Cinco Jotas en su lugar de origen, la sierra de Huelva.",
            "precio_base": 70.0, "ubicacion_lat": 37.9127, "ubicacion_lon": -6.7523,
            "imagen_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Jamón ibérico y cocina serrana", "es_vegano": False,
                    "precio_medio": 70.0, "requiere_reserva": False},
    },
    {
        "id": "rest-020",
        "servicio": {
            "nombre": "La Taberna del Alabardero — Sevilla",
            "descripcion": "Taberna sevillana de referencia en el centro histórico. Tapeo de alta calidad y cocina andaluza.",
            "precio_base": 50.0, "ubicacion_lat": 37.3889, "ubicacion_lon": -5.9953,
            "imagen_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Tapas y cocina andaluza", "es_vegano": False,
                    "precio_medio": 50.0, "requiere_reserva": False},
    },
    {
        "id": "rest-021",
        "servicio": {
            "nombre": "Casa Marcelo — Santiago de Compostela",
            "descripcion": "1 estrella Michelin en el corazón de Santiago. Cocina libre sin carta, menú degustación sorpresa.",
            "precio_base": 120.0, "ubicacion_lat": 42.8806, "ubicacion_lon": -8.5454,
            "imagen_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina gallega de autor", "es_vegano": False,
                    "precio_medio": 120.0, "requiere_reserva": True},
    },
    {
        "id": "rest-022",
        "servicio": {
            "nombre": "Etxebarri — Atxondo, Bizkaia",
            "descripcion": "El mejor asador del mundo según San Pellegrino. Victor Arguinzoniz cocina sobre brasas con leñas autóctonas.",
            "precio_base": 230.0, "ubicacion_lat": 43.0773, "ubicacion_lon": -2.5871,
            "imagen_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina a la brasa de autor", "es_vegano": False,
                    "precio_medio": 230.0, "requiere_reserva": True},
    },
    {
        "id": "rest-023",
        "servicio": {
            "nombre": "La Mar Salada — Barcelona",
            "descripcion": "El mejor restaurante de arroces y mariscos del frente marítimo barcelonés, junto al Port Olímpic.",
            "precio_base": 65.0, "ubicacion_lat": 41.3855, "ubicacion_lon": 2.1975,
            "imagen_url": "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Arroces y mariscos mediterráneos", "es_vegano": False,
                    "precio_medio": 65.0, "requiere_reserva": True},
    },
    {
        "id": "rest-024",
        "servicio": {
            "nombre": "Venta de Aires — Toledo",
            "descripcion": "Taberna toledana desde 1891. Perdiz estofada, carcamusas y caza mayor en pleno corazón de la Mancha.",
            "precio_base": 48.0, "ubicacion_lat": 39.8633, "ubicacion_lon": -4.0268,
            "imagen_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina manchega tradicional", "es_vegano": False,
                    "precio_medio": 48.0, "requiere_reserva": False},
    },
    {
        "id": "rest-025",
        "servicio": {
            "nombre": "El Riff — Valencia",
            "descripcion": "1 estrella Michelin. Chef Bernd Knöller. Cocina mediterránea de autor que mezcla tradición valenciana y técnica europea.",
            "precio_base": 95.0, "ubicacion_lat": 39.4748, "ubicacion_lon": -0.3779,
            "imagen_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina mediterránea de autor", "es_vegano": False,
                    "precio_medio": 95.0, "requiere_reserva": True},
    },
    {
        "id": "rest-026",
        "servicio": {
            "nombre": "Mugaritz — Errenteria, Guipúzcoa",
            "descripcion": "2 estrellas Michelin. Chef Andoni Luis Aduriz. Cocina filosófica entre arte y gastronomía. Top 10 mundial.",
            "precio_base": 240.0, "ubicacion_lat": 43.2684, "ubicacion_lon": -1.8898,
            "imagen_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
            "disponible": True,
        },
        "detalle": {"tipo_cocina": "Cocina conceptual vasca", "es_vegano": False,
                    "precio_medio": 240.0, "requiere_reserva": True},
    },
]

ACTIVIDADES = [
    {
        "id": "acti-001",
        "servicio": {
            "nombre": "Visita guiada a la Sagrada Família — Barcelona",
            "descripcion": "Tour privado con acceso a las torres de la obra maestra de Antoni Gaudí, declarada Patrimonio de la Humanidad.",
            "precio_base": 65.0, "ubicacion_lat": 41.4036, "ubicacion_lon": 2.1744,
            "imagen_url": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 150, "aforo_maximo": 20,
                    "horario_apertura": "09:00 – 20:00", "guia_incluido": True},
    },
    {
        "id": "acti-002",
        "servicio": {
            "nombre": "Tour Alhambra y Generalife — Granada",
            "descripcion": "Visita guiada a la Alhambra, el palacio nazarí mejor conservado del mundo, y sus jardines del Generalife.",
            "precio_base": 50.0, "ubicacion_lat": 37.1771, "ubicacion_lon": -3.5902,
            "imagen_url": "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 180, "aforo_maximo": 30,
                    "horario_apertura": "08:30 – 20:00", "guia_incluido": True},
    },
    {
        "id": "acti-003",
        "servicio": {
            "nombre": "Espectáculo de Flamenco — Sevilla",
            "descripcion": "Tablao flamenco en el barrio de Triana, cuna del flamenco. Show íntimo con bailaores, cantaores y guitarristas profesionales.",
            "precio_base": 45.0, "ubicacion_lat": 37.3828, "ubicacion_lon": -6.0025,
            "imagen_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 90, "aforo_maximo": 40,
                    "horario_apertura": "19:00 – 23:00", "guia_incluido": False},
    },
    {
        "id": "acti-004",
        "servicio": {
            "nombre": "Pintxos tour gastronómico — San Sebastián",
            "descripcion": "Ruta guiada por los mejores bares de pintxos de la Parte Vieja de Donostia. Incluye 8 pintxos y 4 bebidas.",
            "precio_base": 75.0, "ubicacion_lat": 43.3226, "ubicacion_lon": -1.9760,
            "imagen_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 180, "aforo_maximo": 12,
                    "horario_apertura": "19:00 – 22:30", "guia_incluido": True},
    },
    {
        "id": "acti-005",
        "servicio": {
            "nombre": "Senderismo en el Teide — Tenerife",
            "descripcion": "Ascenso guiado al pico del Teide (3715 m), volcán más alto de España y Patrimonio Natural de la Humanidad.",
            "precio_base": 90.0, "ubicacion_lat": 28.2726, "ubicacion_lon": -16.6426,
            "imagen_url": "https://images.unsplash.com/photo-1552084117-56a987666449?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 480, "aforo_maximo": 15,
                    "horario_apertura": "06:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-006",
        "servicio": {
            "nombre": "Kayak y snorkel en las Islas Cíes — Galicia",
            "descripcion": "Excursión en kayak por el archipiélago de las Cíes, Parque Nacional Marítimo-Terrestre. Aguas cristalinas del Atlántico.",
            "precio_base": 60.0, "ubicacion_lat": 42.2277, "ubicacion_lon": -8.9000,
            "imagen_url": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 300, "aforo_maximo": 10,
                    "horario_apertura": "09:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-007",
        "servicio": {
            "nombre": "Visita Museo Guggenheim — Bilbao",
            "descripcion": "Tour guiado por el icónico museo de arte contemporáneo de Frank Gehry, símbolo del efecto Bilbao.",
            "precio_base": 18.0, "ubicacion_lat": 43.2688, "ubicacion_lon": -2.9341,
            "imagen_url": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 150, "aforo_maximo": 20,
                    "horario_apertura": "10:00 – 20:00", "guia_incluido": True},
    },
    {
        "id": "acti-008",
        "servicio": {
            "nombre": "Surf en Mundaka — País Vasco",
            "descripcion": "Clases de surf en Mundaka, hogar de una de las olas de izquierda más largas de Europa. Para todos los niveles.",
            "precio_base": 70.0, "ubicacion_lat": 43.4059, "ubicacion_lon": -2.6987,
            "imagen_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 180, "aforo_maximo": 8,
                    "horario_apertura": "09:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-009",
        "servicio": {
            "nombre": "Ruta del Vino La Rioja — Haro y Logroño",
            "descripcion": "Tour en minibús por las bodegas más históricas de La Rioja. Incluye 5 catas y maridaje.",
            "precio_base": 95.0, "ubicacion_lat": 42.5769, "ubicacion_lon": -2.8499,
            "imagen_url": "https://images.unsplash.com/photo-1552084117-56a987666449?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 360, "aforo_maximo": 16,
                    "horario_apertura": "10:00 – 19:00", "guia_incluido": True},
    },
    {
        "id": "acti-010",
        "servicio": {
            "nombre": "Visita Mezquita-Catedral — Córdoba",
            "descripcion": "Tour guiado por la Mezquita-Catedral de Córdoba, la joya del arte islámico en Occidente.",
            "precio_base": 25.0, "ubicacion_lat": 37.8789, "ubicacion_lon": -4.7794,
            "imagen_url": "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 120, "aforo_maximo": 25,
                    "horario_apertura": "09:30 – 19:00", "guia_incluido": True},
    },
    {
        "id": "acti-011",
        "servicio": {
            "nombre": "Senderismo Picos de Europa — Asturias",
            "descripcion": "Ruta guiada por el Parque Nacional de los Picos de Europa. Lagos glaciares y picos de más de 2.600m.",
            "precio_base": 65.0, "ubicacion_lat": 43.1947, "ubicacion_lon": -4.8481,
            "imagen_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 480, "aforo_maximo": 12,
                    "horario_apertura": "08:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-012",
        "servicio": {
            "nombre": "Excursión a Montserrat — Cataluña",
            "descripcion": "Excursión guiada a la montaña de Montserrat. Monasterio benedictino, vistas únicas y senderismo.",
            "precio_base": 55.0, "ubicacion_lat": 41.5931, "ubicacion_lon": 1.8340,
            "imagen_url": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 360, "aforo_maximo": 20,
                    "horario_apertura": "09:00 – 19:00", "guia_incluido": True},
    },
    {
        "id": "acti-013",
        "servicio": {
            "nombre": "Kitesurf en Tarifa — Cádiz",
            "descripcion": "Clases de kitesurf en Tarifa, capital mundial del viento. El estrecho de Gibraltar crea las condiciones perfectas.",
            "precio_base": 120.0, "ubicacion_lat": 36.0144, "ubicacion_lon": -5.6044,
            "imagen_url": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 240, "aforo_maximo": 6,
                    "horario_apertura": "09:00 – 19:00", "guia_incluido": True},
    },
    {
        "id": "acti-014",
        "servicio": {
            "nombre": "Esquí en Sierra Nevada — Granada",
            "descripcion": "Jornada de esquí en Sierra Nevada, la única estación de España con vistas al Mediterráneo. 110 km de pistas.",
            "precio_base": 85.0, "ubicacion_lat": 37.0945, "ubicacion_lon": -3.3984,
            "imagen_url": "https://images.unsplash.com/photo-1552084117-56a987666449?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 480, "aforo_maximo": 30,
                    "horario_apertura": "09:00 – 17:00", "guia_incluido": False},
    },
    {
        "id": "acti-015",
        "servicio": {
            "nombre": "Vela en Ibiza — Baleares",
            "descripcion": "Travesía en velero privado alrededor de Ibiza y Formentera. Snorkel en calas secretas.",
            "precio_base": 180.0, "ubicacion_lat": 38.9067, "ubicacion_lon": 1.4206,
            "imagen_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 480, "aforo_maximo": 8,
                    "horario_apertura": "09:00 – 19:00", "guia_incluido": True},
    },
    {
        "id": "acti-016",
        "servicio": {
            "nombre": "Visita Ciudad de las Artes y las Ciencias — Valencia",
            "descripcion": "Tour completo por el complejo arquitectónico de Santiago Calatrava. Oceanogràfic, Hemisfèric y Museu de les Ciències.",
            "precio_base": 38.0, "ubicacion_lat": 39.4545, "ubicacion_lon": -0.3507,
            "imagen_url": "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 360, "aforo_maximo": 35,
                    "horario_apertura": "10:00 – 21:00", "guia_incluido": True},
    },
    {
        "id": "acti-017",
        "servicio": {
            "nombre": "Surf en Fuerteventura — Canarias",
            "descripcion": "Clases de surf en la isla canaria con las mejores olas de Europa. Playas de El Cotillo y Corralejo.",
            "precio_base": 75.0, "ubicacion_lat": 28.3596, "ubicacion_lon": -14.0537,
            "imagen_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 180, "aforo_maximo": 8,
                    "horario_apertura": "09:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-018",
        "servicio": {
            "nombre": "Ruta gastronómica por el Mercado Central — Valencia",
            "descripcion": "Tour guiado por el Mercado Central de Valencia con degustaciones. Naranja, horchata, fideuà y pimentón.",
            "precio_base": 55.0, "ubicacion_lat": 39.4737, "ubicacion_lon": -0.3797,
            "imagen_url": "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 150, "aforo_maximo": 15,
                    "horario_apertura": "09:00 – 14:00", "guia_incluido": True},
    },
    {
        "id": "acti-019",
        "servicio": {
            "nombre": "Visita Alcázar de Segovia",
            "descripcion": "Tour guiado por el Alcázar de Segovia, el castillo que inspiró el Castillo de Cenicienta de Disney.",
            "precio_base": 20.0, "ubicacion_lat": 40.9528, "ubicacion_lon": -4.1306,
            "imagen_url": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 120, "aforo_maximo": 25,
                    "horario_apertura": "10:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-020",
        "servicio": {
            "nombre": "Senderismo Camino Primitivo — Asturias",
            "descripcion": "Primera etapa del Camino de Santiago más antiguo. Ruta de montaña entre Oviedo y Lugo.",
            "precio_base": 45.0, "ubicacion_lat": 43.3614, "ubicacion_lon": -5.8496,
            "imagen_url": "https://images.unsplash.com/photo-1552084117-56a987666449?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 420, "aforo_maximo": 12,
                    "horario_apertura": "07:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-021",
        "servicio": {
            "nombre": "Cuevas de Altamira — Cantabria",
            "descripcion": "Visita al Neocueva de Altamira, réplica exacta de las pinturas rupestres más famosas del mundo.",
            "precio_base": 12.0, "ubicacion_lat": 43.3786, "ubicacion_lon": -4.1068,
            "imagen_url": "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 90, "aforo_maximo": 20,
                    "horario_apertura": "09:30 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-022",
        "servicio": {
            "nombre": "Visita Teatre-Museu Dalí — Figueres",
            "descripcion": "Tour guiado por el museo más visitado de España después del Prado. El universo surrealista de Dalí.",
            "precio_base": 22.0, "ubicacion_lat": 42.2676, "ubicacion_lon": 2.9607,
            "imagen_url": "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 120, "aforo_maximo": 20,
                    "horario_apertura": "09:00 – 18:00", "guia_incluido": True},
    },
    {
        "id": "acti-023",
        "servicio": {
            "nombre": "Ruta en barco por la Costa Brava — Girona",
            "descripcion": "Excursión en barco desde Palamós con paradas en calas vírgenes. Fondo marino cristalino.",
            "precio_base": 65.0, "ubicacion_lat": 41.8470, "ubicacion_lon": 3.1319,
            "imagen_url": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 300, "aforo_maximo": 20,
                    "horario_apertura": "10:00 – 17:00", "guia_incluido": True},
    },
    {
        "id": "acti-024",
        "servicio": {
            "nombre": "Parasailing en Benalmádena — Málaga",
            "descripcion": "Vuelo en parasailing sobre la Costa del Sol desde la marina de Benalmádena. Vistas a Gibraltar y África.",
            "precio_base": 55.0, "ubicacion_lat": 36.5988, "ubicacion_lon": -4.5165,
            "imagen_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 60, "aforo_maximo": 2,
                    "horario_apertura": "10:00 – 19:00", "guia_incluido": False},
    },
    {
        "id": "acti-025",
        "servicio": {
            "nombre": "Visita Catedral de Burgos",
            "descripcion": "Tour guiado por la Catedral de Burgos, obra maestra del gótico español y Patrimonio de la Humanidad.",
            "precio_base": 15.0, "ubicacion_lat": 42.3408, "ubicacion_lon": -3.7038,
            "imagen_url": "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 90, "aforo_maximo": 25,
                    "horario_apertura": "09:30 – 19:30", "guia_incluido": True},
    },
    {
        "id": "acti-026",
        "servicio": {
            "nombre": "Enoturismo en Penedès — Cataluña",
            "descripcion": "Visita a bodegas centenarias del Alt Penedès con cata de cavas y vinos DO Penedès. Incluye maridaje.",
            "precio_base": 80.0, "ubicacion_lat": 41.4834, "ubicacion_lon": 1.6830,
            "imagen_url": "https://images.unsplash.com/photo-1552084117-56a987666449?w=800",
            "disponible": True,
        },
        "detalle": {"duracion_estimada": 300, "aforo_maximo": 15,
                    "horario_apertura": "10:00 – 18:00", "guia_incluido": True},
    },
]


class Command(BaseCommand):
    help = "Crea 6 servicios de cada tipo con sus detalles (idempotente)."

    def handle(self, *args, **options):
        self.stdout.write("Creando tipos de servicio...")
        tipos = {}
        for data in TIPOS:
            tipo, created = TipoServicio.objects.get_or_create(
                nombre_tipo=data["nombre_tipo"],
                defaults={"icono": data["icono"]},
            )
            tipos[data["nombre_tipo"]] = tipo
            self.stdout.write(f"  {'[+]' if created else '[ ]'} {tipo.nombre_tipo}")

        datasets = [
            ("Alojamiento",  ALOJAMIENTOS,  DetalleAlojamiento),
            ("Transporte",   TRANSPORTES,   DetalleTransporte),
            ("Restauración", RESTAURACIONES, DetalleRestauracion),
            ("Actividad",    ACTIVIDADES,   DetalleActividad),
        ]

        for tipo_nombre, items, DetalleModel in datasets:
            tipo_obj = tipos[tipo_nombre]
            self.stdout.write(f"\nServicios de {tipo_nombre}:")
            for item in items:
                servicio, created = CatalogoServicio.objects.get_or_create(
                    id_servicio=item["id"],
                    defaults={**item["servicio"], "tipo": tipo_obj},
                )
                DetalleModel.objects.get_or_create(
                    servicio=servicio,
                    defaults=item["detalle"],
                )
                self.stdout.write(f"  {'[+]' if created else '[ ]'} {servicio.nombre}")

        self.stdout.write(self.style.SUCCESS("\n✓ Seed completado: 4 tipos, 24 servicios."))
