# Generated by Django 4.2 on 2026-02-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlan',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('api_provider_id', models.TextField(blank=True, null=True)),
                ('nombre_servicio', models.TextField(blank=True, null=True)),
                ('ubicacion_lat', models.FloatField(blank=True, null=True)),
                ('ubicacion_lon', models.FloatField(blank=True, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('precio_estimado', models.FloatField(blank=True, null=True)),
                ('datos_json', models.TextField(blank=True, help_text='JSON embebido para detalles especificos', null=True)),
            ],
            options={
                'db_table': 'ITEMS_PLAN',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('localizador_confirmacion', models.TextField(blank=True, null=True)),
                ('estado_pago', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], max_length=20, null=True)),
                ('monto_total', models.FloatField(blank=True, null=True)),
                ('fecha_transaccion', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(blank=True, db_column='id_item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='planning.itemplan')),
            ],
            options={
                'db_table': 'RESERVAS',
            },
        ),
        migrations.CreateModel(
            name='PlanViaje',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_plan', models.CharField(blank=True, choices=[('Borrador', 'Borrador'), ('Confirmado', 'Confirmado'), ('Finalizado', 'Finalizado')], max_length=20, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_viaje', to='core.customuser')),
            ],
            options={
                'db_table': 'PLANES_VIAJE',
            },
        ),
        migrations.AddField(
            model_name='itemplan',
            name='plan',
            field=models.ForeignKey(blank=True, db_column='id_plan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.planviaje'),
        ),
        migrations.AddField(
            model_name='itemplan',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketdata.tiposervicio'),
        ),
    ]
