# Generated by Django 4.2 on 2026-02-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplan',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketdata.tiposervicio'),
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
